### ISSUE TITLE
We need a README

### ISSUE THREAD

**Issue by quantum818** [xizeyoupan/SAOM#1]
说明呢说明呢说明呢说明呢说明呢说明呢说明呢说明呢说明呢说明呢说明呢说明呢说明呢说明呢说明呢说明呢说明呢说明呢说明呢说明呢说明呢说明呢说明呢说明呢说明呢说明呢说明呢说明呢说明呢说明呢说明呢说明呢说明呢说明呢说明呢说明呢说明呢说明呢说明呢说明呢说明呢说明呢说明呢说明呢说明呢说明呢说明呢说明呢说明呢说明呢说明呢说明呢

**Comment by xizeyoupan** [comment]
pr welcome

**Comment by xizeyoupan** [comment]
Now we have pretty docs.🤞
